[package]
name = "rudo"
version = "0.1.0"
authors = ["shawnanastasio"]
build="build.rs"

[build-dependencies]
gcc = "0.3"

[dependencies]
rpassword = "0.4.0"
serde = "1.0.7"
serde_derive = "1.0.7"
serde_json = "1.0.2"
getopts = "0.2.14"
users = "0.5.2"
