[package]
name = "rudo"
version = "0.1.0"
authors = ["shawnanastasio"]
build = "build.rs"

[build-dependencies]
cc = "1.0"

[dependencies]
rpassword = "2.0.0"
serde = "1.0.27"
serde_derive = "1.0.27"
serde_json = "1.0.9"
getopts = "0.2.17"
users = "0.6.0"
time = "0.1.39"
libc = "0.2.23"

[features]
default = ["pam"]

# Use pam authentication
pam = []

# If this feature is specified, support for TouchID will be compiled in
# using the CLocalAuthentication library. Obviously only supported on macOS.
touchid = ["pam"]
