[package]
name = "rudo"
version = "0.1.0"
authors = ["shawnanastasio"]
build = "build.rs"

[build-dependencies]
gcc = "0.3"

[dependencies]
rpassword = "0.4.0"
serde = "1.0.7"
serde_derive = "1.0.7"
serde_json = "1.0.2"
getopts = "0.2.14"
users = "0.5.2"
time = "0.1.37"
libc = "0.2.24"

[features]
default = []

# If this feature is specified, support for TouchID will be compiled in
# using the CLocalAuthentication library. Obviously only supported on macOS.
touchid = []